### ISSUE TITLE
Aliases for small-step and type-as

### ISSUE THREAD

**Issue by Kile-Asmussen** [pietervdvn/ALGT2#3]
The small-step declaration uses U+2192 (→)

The type-as declaration uses U+003A U+003A (::)

Why not allow U+002D U+003E (->) as small-step and U+2237 (∷) as type-as?

**Comment by pietervdvn** [comment]
Hey there Karl,

This is a relations which you declare in ALGT. You are totally free to pick the symbol of the relation.

So if you want to create a smallstep with symbol `->`; go ahead!  I thought it was neater (although more difficult) to use the unicode symbol.

If you mean to allow both symbols for the relation, mixed; that is not possible for now and will imho clutter the implementation.

I might make a 'sugared' version of ALGT one day, in which I might add support for having multiple symbols for one relation.

I've also noted this in the tutorial itself.
